server:
  port: 8989
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.0.0.1:3306/mybatis01?useUnicode=true&characterEncoding=utf8
    data-username: root
    password: root1234






